server {
    listen 8081;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ \.js$ {
        include /etc/nginx/mime.types;
        add_header Content-Type application/javascript;
    }

    location = /admin.html {
        try_files $uri =404;
    }
}