services:
  frontend:
    image: ghcr.io/mstefn/gym-frontend:latest
    container_name: gym-frontend
    restart: always
    ports:
      - "80:80" 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - gym_app_net
    depends_on:
      - backend

  backend:
    image: ghcr.io/mstefn/gym-backend:latest
    container_name: gym-backend
    restart: always
    expose:
      - "4000" 
    env_file: .env
    environment:
      - DB_DSN=${DB_DSN}
      - AUTH_SECRET=${AUTH_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
    depends_on:
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - gym_app_net
      - gym_monitor_net 

  db:
    image: mariadb:10.11
    container_name: gym-db
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mariadb:/var/lib/mysql  # MAPOWANIE NA DYSK
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - gym_app_net

networks:
  gym_app_net:
    driver: bridge
  gym_monitor_net:
    external: true