services:
  db:
    image: mariadb:10.11
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:4000"
    env_file: .env
    environment:
      - DB_DSN=${DB_DSN}
      - AUTH_SECRET=${AUTH_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5000:8081"
    restart: always

volumes:
  mariadb_data:
