global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gym-backend'
    static_configs:
      - targets: ['backend:4000'] 

  - job_name: 'gym-cadvisor'
    static_configs:
      - targets: ['cadvisor:8080'] 